{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm.fullname" . }}-config
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
data:
  litellm_config.yaml: |
    {{- .Values.configMap.litellm_config_yaml | nindent 4 }}
{{- end }}
